spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.datasource.url=${BIDDING_DB_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bidmart}}
spring.datasource.username=${BIDDING_DB_USERNAME:${SPRING_DATASOURCE_USERNAME:postgres}}
spring.datasource.password=${BIDDING_DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:postgres}}
